/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Assignment2;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ASUS ROG
 */
public class AdmindashboardForm extends javax.swing.JFrame {
    
    DefaultTableModel model;

    /**
     * Creates new form AdmindashboardForm
     */
    public AdmindashboardForm() {
        initComponents();
        model = (DefaultTableModel) table.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_username3 = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();
        btn_resetpassword = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        txt_password3 = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        txt_confirmpassword = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_newpassword = new javax.swing.JPasswordField();
        btn_submit = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        txt_username4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txt_search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        btn_logout1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(516, 306));

        jLabel1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel1.setText("Username :");

        jLabel4.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel4.setText("Password :");

        txt_username3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_username3ActionPerformed(evt);
            }
        });
        txt_username3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_username3KeyTyped(evt);
            }
        });

        btn_add.setBackground(new java.awt.Color(51, 204, 0));
        btn_add.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btn_add.setText("ADD");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_resetpassword.setBackground(new java.awt.Color(153, 153, 153));
        btn_resetpassword.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btn_resetpassword.setText("RESET PASSWORD");
        btn_resetpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetpasswordActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(255, 102, 102));
        btn_delete.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btn_delete.setText("DELETE");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_edit.setBackground(new java.awt.Color(0, 204, 255));
        btn_edit.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btn_edit.setText("EDIT");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        table.setBackground(new java.awt.Color(204, 255, 204));
        table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Username", "Password"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        table.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tableInputMethodTextChanged(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_username3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_password3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_resetpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(btn_edit)
                        .addGap(6, 6, 6)
                        .addComponent(btn_delete)
                        .addGap(8, 8, 8)
                        .addComponent(btn_add))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(txt_username3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(txt_password3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_resetpassword)
                    .addComponent(btn_edit)
                    .addComponent(btn_delete)
                    .addComponent(btn_add))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Create User", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(516, 306));

        jLabel8.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel8.setText("New Password :");

        jLabel9.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel9.setText("Confirm Password :");

        btn_submit.setBackground(new java.awt.Color(51, 204, 0));
        btn_submit.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btn_submit.setText("SUBMIT");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        btn_clear.setBackground(new java.awt.Color(153, 153, 153));
        btn_clear.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btn_clear.setText("CLEAR");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        txt_username4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_username4ActionPerformed(evt);
            }
        });
        txt_username4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_username4KeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel3.setText("Username :");

        jButton1.setBackground(new java.awt.Color(153, 255, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jButton1.setText("NEXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setText("Reset Password");

        jButton2.setBackground(new java.awt.Color(255, 255, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("$   €   £   ¥  ₹   A $   C $   CHF   ₽   ₩   R$   R   ₺   Rp   S$   R M   ฿");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_confirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(btn_submit))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(txt_username4, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(txt_newpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(184, 184, 184))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_username4, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_newpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_confirmpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_clear)
                    .addComponent(btn_submit)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(35, 35, 35)
                .addComponent(jLabel14)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Reset", jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel2.setText("Search :");

        table1.setBackground(new java.awt.Color(204, 255, 204));
        table1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Username", "Password"
            }
        ));
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        table1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                table1InputMethodTextChanged(evt);
            }
        });
        jScrollPane3.setViewportView(table1);

        btn_logout1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btn_logout1.setText("LOGOUT");
        btn_logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logout1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_logout1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txt_search)))
                .addGap(65, 65, 65))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_logout1)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Search", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logout1ActionPerformed
        // TODO add your handling code here:
        // Show a confirmation dialog
    int response = JOptionPane.showConfirmDialog(this, 
        "Are you sure you want to log out?", 
        "Logout Confirmation", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.QUESTION_MESSAGE);

    // Check the user's response
    if (response == JOptionPane.YES_OPTION) {
        // If the user clicked "Yes", proceed with logout
        (new loginForm()).setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_btn_logout1ActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        txt_search.setText(null);
        txt_newpassword.setText(null);
        txt_confirmpassword.setText(null);
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        String username = txt_username4.getText();
        String newPassword = txt_newpassword.getText();
        String confirmPassword = txt_confirmpassword.getText();

    if (username.isEmpty() || newPassword.isEmpty() || confirmPassword.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Oops! All fields must be filled out!");
    } else if (!newPassword.equals(confirmPassword)) {
    JOptionPane.showMessageDialog(null, "Passwords do not match! Please try again.");
    } else {
    try {
        File inputFile = new File("btn_add.txt");
        File tempFile = new File("temp_btn_add.txt");

        BufferedReader reader = new BufferedReader(new FileReader(inputFile));
        FileWriter writer = new FileWriter(tempFile);

        String currentLine;
        boolean passwordUpdated = false;

        while ((currentLine = reader.readLine()) != null) {
            if (currentLine.startsWith(username + ",")) {
                writer.write(username + "," + newPassword + System.lineSeparator());
                passwordUpdated = true;
            } else {
                writer.write(currentLine + System.lineSeparator());
            }
        }

        reader.close();
        writer.close();

        if (inputFile.delete() && tempFile.renameTo(inputFile)) {
            if (passwordUpdated) {
                JOptionPane.showMessageDialog(null, "Password updated successfully!");

                // Update the table data
                DefaultTableModel model1 = (DefaultTableModel) table.getModel();
                DefaultTableModel model2 = (DefaultTableModel) table1.getModel();
                model1.setRowCount(0); // Clear existing rows in table
                model2.setRowCount(0); // Clear existing rows in table1

                BufferedReader refreshReader = new BufferedReader(new FileReader("btn_add.txt"));
                String line;
                while ((line = refreshReader.readLine()) != null) {
                    String[] data = line.split(",");
                    if (data.length == 2) { // Ensure valid username and password pair
                        model1.addRow(new Object[]{data[0], data[1]});
                        model2.addRow(new Object[]{data[0], data[1]});
                    }
                }
                refreshReader.close();
            } else {
                JOptionPane.showMessageDialog(null, "Username not found! Cannot update password.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Error updating password. Please try again.");
        }

        txt_newpassword.setText("");
        txt_confirmpassword.setText("");
        txt_username4.setText("");
    } catch (IOException e) {
        System.err.println("Error: " + e.getMessage());
    }
    } 
    }//GEN-LAST:event_btn_submitActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:
        DefaultTableModel obj = (DefaultTableModel) table1.getModel();
        TableRowSorter<DefaultTableModel> obj1 = new TableRowSorter<>(obj);
        table1.setRowSorter(obj1);
        obj1.setRowFilter(RowFilter.regexFilter(txt_search.getText()));
    }//GEN-LAST:event_txt_searchKeyReleased

    private void table1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_table1InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_table1InputMethodTextChanged

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_table1MouseClicked

    private void tableInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tableInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tableInputMethodTextChanged

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        // Add MouseListener to the jTable
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                // Get the selected row index
                int selectedRow = table.getSelectedRow();

                // Ensure the selected row index is valid
                if (selectedRow != -1) {
                    // Retrieve data from the selected row
                    String username = table.getValueAt(selectedRow, 0).toString(); // Assuming username is in column 0
                    String password = table.getValueAt(selectedRow, 1).toString(); // Assuming password is in column 1

                    // Set the retrieved values into the text fields
                    txt_username3.setText(username);
                    txt_password3.setText(password);
                }
            }
        });
    }//GEN-LAST:event_tableMouseClicked

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // Retrieve new values from input fields
    String newUsername = txt_username3.getText();
    String newPassword = txt_password3.getText();

    // Get models for both tables
    DefaultTableModel tblModel1 = (DefaultTableModel) table.getModel();
    DefaultTableModel tblModel2 = (DefaultTableModel) table1.getModel();

    // Check if a row is selected in table
    int selectedRow = table.getSelectedRow();
    int selectedRow1 = table1.getSelectedRow();

    if (selectedRow != -1 || selectedRow1 != -1) {
    try {
        String oldUsername;

        // Update Table
        if (selectedRow != -1) {
            oldUsername = (String) tblModel1.getValueAt(selectedRow, 0);
            tblModel1.setValueAt(newUsername, selectedRow, 0);
            tblModel1.setValueAt(newPassword, selectedRow, 1);
            tblModel2.setValueAt(newUsername, selectedRow, 0); // Sync table1 too
            tblModel2.setValueAt(newPassword, selectedRow, 1);
        } else {
            oldUsername = (String) tblModel2.getValueAt(selectedRow1, 0);
            tblModel2.setValueAt(newUsername, selectedRow1, 0);
            tblModel2.setValueAt(newPassword, selectedRow1, 1);
            tblModel1.setValueAt(newUsername, selectedRow1, 0); // Sync table too
            tblModel1.setValueAt(newPassword, selectedRow1, 1);
        }

        // Update the file
        File inputFile = new File("btn_add.txt");
        File tempFile = new File("temp_btn_add.txt");

        BufferedReader reader = new BufferedReader(new FileReader(inputFile));
        FileWriter writer = new FileWriter(tempFile);

        String currentLine;
        while ((currentLine = reader.readLine()) != null) {
            if (currentLine.startsWith(oldUsername + ",")) {
                writer.write(newUsername + "," + newPassword + System.lineSeparator());
            } else {
                writer.write(currentLine + System.lineSeparator());
            }
        }

        reader.close();
        writer.close();

        // Replace the original file with the updated file
        if (inputFile.delete() && tempFile.renameTo(inputFile)) {
            JOptionPane.showMessageDialog(this, "Update Successful in Tables and File!");
        } else {
            JOptionPane.showMessageDialog(this, "Error updating file. Please try again.");
        }

    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    } else {
    // Handle cases where no rows are selected
    if (table.getRowCount() == 0 && table1.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, "Both tables are empty.");
    } else {
        JOptionPane.showMessageDialog(this, "Please select a single row from the Table for update.");
    }
    }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // Get models for both tables
        DefaultTableModel tblModel1 = (DefaultTableModel) table.getModel();
        DefaultTableModel tblModel2 = (DefaultTableModel) table1.getModel();

        // Check if a row is selected in either table
        int selectedRow = table.getSelectedRow();
        int selectedRow1 = table1.getSelectedRow();

        if (selectedRow != -1 || selectedRow1 != -1) {
        
            try {
        // Identify the row to be deleted (prioritize table)
        String usernameToDelete;
        if (selectedRow != -1) {
            usernameToDelete = (String) tblModel1.getValueAt(selectedRow, 0);
            tblModel1.removeRow(selectedRow);
            tblModel2.removeRow(selectedRow);
        } else {
            usernameToDelete = (String) tblModel2.getValueAt(selectedRow1, 0);
            tblModel1.removeRow(selectedRow1);
            tblModel2.removeRow(selectedRow1);
        }

        // Read the file and rewrite it without the deleted username
        File inputFile = new File("btn_add.txt");
        File tempFile = new File("temp_btn_add.txt");

        BufferedReader reader = new BufferedReader(new FileReader(inputFile));
        FileWriter writer = new FileWriter(tempFile);

        String currentLine;
        while ((currentLine = reader.readLine()) != null) {
            if (!currentLine.startsWith(usernameToDelete + ",")) {
                writer.write(currentLine + System.lineSeparator());
            }
        }

        reader.close();
        writer.close();

        // Replace the original file with the updated file
        if (inputFile.delete() && tempFile.renameTo(inputFile)) {
            JOptionPane.showMessageDialog(this, "Row deleted from Table, Table1, and file.");
        } else {
            JOptionPane.showMessageDialog(this, "Error updating file. Please try again.");
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    } 
        else {
    // Handle cases where no rows are selected
    if (table.getRowCount() == 0 && table1.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, "Both tables are empty.");
    } else {
        JOptionPane.showMessageDialog(this, "Please select a single row from the Table for deletion.");
    }
    }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_resetpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetpasswordActionPerformed
        jTabbedPane1.setSelectedComponent(jPanel2);
    }//GEN-LAST:event_btn_resetpasswordActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // Check if username or password fields are empty
        String username = txt_username3.getText();
        String password = txt_password3.getText();
        
        try {
        // Writing to the file
        FileWriter writer = new FileWriter("btn_add.txt", true);
        writer.write(username + "," + password);
        writer.write(System.getProperty("line.separator")); // Adds a new line
        writer.close();
    
        // You can add additional logic here if needed, such as clearing input fields or updating a UI component
        } catch (IOException e) {
        System.err.println("Error: " + e.getMessage()); // Log the error in the console
        }

        if (txt_username3.getText().isEmpty() || txt_password3.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Oops! You missed something! Fill out both the username and password to keep the rizz!");
        } else {
            // Get the table model for both tables
            DefaultTableModel tblModel1 = (DefaultTableModel) table.getModel();
            DefaultTableModel tblModel2 = (DefaultTableModel) table1.getModel();

            // Add username and password to both tables
            tblModel1.insertRow(0, new Object[] {
                txt_username3.getText(),
                txt_password3.getText()
            });
            tblModel2.insertRow(0, new Object[] {
                txt_username3.getText(),
                txt_password3.getText()
            });

            JOptionPane.showMessageDialog(null, "Naise! Your record’s locked in, and you've scored some aura points, with all data successfully added to both profiles!");

            // Clear the text fields after adding the data
            txt_username3.setText("");
            txt_password3.setText("");
        } 
    }//GEN-LAST:event_btn_addActionPerformed

    private void txt_username3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_username3KeyTyped

    }//GEN-LAST:event_txt_username3KeyTyped

    private void txt_username3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_username3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_username3ActionPerformed

    private void txt_username4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_username4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_username4ActionPerformed

    private void txt_username4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_username4KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_username4KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedComponent(jPanel3);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedComponent(jPanel1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedComponent(jPanel2);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmindashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmindashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmindashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmindashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdmindashboardForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_logout1;
    private javax.swing.JButton btn_resetpassword;
    private javax.swing.JButton btn_submit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable table;
    private javax.swing.JTable table1;
    private javax.swing.JPasswordField txt_confirmpassword;
    private javax.swing.JPasswordField txt_newpassword;
    private javax.swing.JPasswordField txt_password3;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_username3;
    private javax.swing.JTextField txt_username4;
    // End of variables declaration//GEN-END:variables
}