package Assignment2;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS ROG
 */
public class UserdashboardForm extends javax.swing.JFrame {

    /**
     * Creates new form UserdashboardForm
     */
    public UserdashboardForm() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_income = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_expenses = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        btn_clear = new javax.swing.JButton();
        btn_submit = new javax.swing.JButton();
        lbl_netbalance = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_income = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbl_expenses = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_next = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        btn_erase = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_next1 = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_saving = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_monthly = new javax.swing.JTextField();
        txt_amount = new javax.swing.JTextField();
        btn_enter = new javax.swing.JButton();
        btn_undo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_result = new javax.swing.JTextArea();
        txt_item = new javax.swing.JTextField();
        btn_logout2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(516, 306));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(516, 306));

        jLabel3.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel3.setText("Name:");

        jLabel2.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel2.setText("Income: RM");

        jLabel4.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel4.setText("Expenses: RM");

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setText("Personal Finance Application");

        btn_clear.setBackground(new java.awt.Color(153, 153, 153));
        btn_clear.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_submit.setBackground(new java.awt.Color(51, 204, 0));
        btn_submit.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        lbl_netbalance.setText("$$$$$$");

        jLabel8.setText("Total Income:");

        lbl_income.setText("$$$$");

        jLabel10.setText("Total Expenses:");

        lbl_expenses.setText("$$$");

        jLabel11.setText("Net Balance:");

        btn_next.setBackground(new java.awt.Color(153, 255, 204));
        btn_next.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btn_next.setText("Next");
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel12.setText("Quick Calculation");

        jLabel13.setText("_______________________");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("$   €   £   ¥  ₹   A $   C $   CHF   ₽   ₩   R$   R   ₺   Rp   S$   R M   ฿");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_income, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_expenses)
                                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_next, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_submit)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_income))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_expenses))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_netbalance))
                            .addComponent(jLabel12)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)))
                .addGap(82, 82, 82))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_income, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(lbl_income))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_expenses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10)
                    .addComponent(lbl_expenses))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_clear)
                    .addComponent(btn_next)
                    .addComponent(btn_submit)
                    .addComponent(jLabel11)
                    .addComponent(lbl_netbalance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
        );

        jTabbedPane1.addTab("User Dashboard", jPanel2);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(516, 306));

        table2.setBackground(new java.awt.Color(204, 255, 255));
        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Income (RM)", "Expenses (RM)"
            }
        ));
        table2.setGridColor(new java.awt.Color(204, 255, 204));
        table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table2);

        btn_erase.setBackground(new java.awt.Color(255, 102, 102));
        btn_erase.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btn_erase.setText("Erase");
        btn_erase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eraseActionPerformed(evt);
            }
        });

        btn_update.setBackground(new java.awt.Color(204, 255, 255));
        btn_update.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_next1.setBackground(new java.awt.Color(153, 255, 204));
        btn_next1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btn_next1.setText("Next");
        btn_next1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_next1ActionPerformed(evt);
            }
        });

        btn_back.setBackground(new java.awt.Color(255, 255, 204));
        btn_back.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_update)
                .addGap(18, 18, 18)
                .addComponent(btn_back)
                .addGap(18, 18, 18)
                .addComponent(btn_next1)
                .addGap(18, 18, 18)
                .addComponent(btn_erase)
                .addGap(89, 89, 89))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_erase)
                    .addComponent(btn_update)
                    .addComponent(btn_next1)
                    .addComponent(btn_back))
                .addGap(31, 31, 31))
        );

        jTabbedPane1.addTab("Financial Overview", jPanel1);

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(516, 306));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setText("What you want to buy?");

        jLabel6.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel6.setText(" Savings : RM");

        jLabel7.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel7.setText("Monthly : RM");

        jLabel9.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel9.setText("Amount : RM");

        btn_enter.setBackground(new java.awt.Color(153, 255, 204));
        btn_enter.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btn_enter.setText("Enter");
        btn_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enterActionPerformed(evt);
            }
        });

        btn_undo.setBackground(new java.awt.Color(153, 153, 153));
        btn_undo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btn_undo.setText("Undo");
        btn_undo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_undoActionPerformed(evt);
            }
        });

        txt_result.setColumns(20);
        txt_result.setRows(5);
        jScrollPane2.setViewportView(txt_result);

        btn_logout2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btn_logout2.setText("Logout");
        btn_logout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logout2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_logout2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_saving, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_monthly, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_item, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_undo)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(btn_enter)
                                .addGap(61, 61, 61)))
                        .addGap(80, 80, 80))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_saving, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_monthly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_undo)
                    .addComponent(jButton1)
                    .addComponent(btn_enter))
                .addGap(18, 18, 18)
                .addComponent(btn_logout2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Results", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logout2ActionPerformed
        // TODO add your handling code here:
        // Show a confirmation dialog
    int response = JOptionPane.showConfirmDialog(this, 
        "Are you sure you want to log out?", 
        "Logout Confirmation", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.QUESTION_MESSAGE);

    // Check the user's response
    if (response == JOptionPane.YES_OPTION) {
        // If the user clicked "Yes", proceed with logout
        new loginForm().setVisible(true);  // Open the login form
        this.dispose();  // Close the current form
    }
    // If the user clicked "No", do nothing and stay on the current form
    }//GEN-LAST:event_btn_logout2ActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
    DefaultTableModel tblModel = (DefaultTableModel) table2.getModel();
    int selectedRow = table2.getSelectedRow();

    if (table2.getSelectedRowCount() == 1) {
    // Retrieve new values from input fields
    String name = txt_name.getText();
    String incomeStr = txt_income.getText();
    String expensesStr = txt_expenses.getText();

    // Parse income and expenses to double for statistical calculations
    double income = Double.parseDouble(incomeStr);
    double expenses = Double.parseDouble(expensesStr);
    double netBalance = income - expenses;

    // Get the old name from the selected row
    String oldName = (String) tblModel.getValueAt(selectedRow, 0);

    // Update the table model with new values
    tblModel.setValueAt(name, selectedRow, 0);
    tblModel.setValueAt(incomeStr, selectedRow, 1);
    tblModel.setValueAt(expensesStr, selectedRow, 2);

    // Write the updated data to the file
    try {
        FileWriter writer = new FileWriter("btn_add.txt", true);
        writer.write(name + "," + income + "," + expenses);
        writer.write(System.getProperty("line.separator")); // Adds a new line
        writer.close();
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error updating file: " + e.getMessage());
    }

    // Display success message
    JOptionPane.showMessageDialog(this, "Update Successful!");

    // Create and populate the pie dataset
    DefaultPieDataset pieDataset = new DefaultPieDataset();
    pieDataset.setValue("Income", income);
    pieDataset.setValue("Expenses", expenses);
    pieDataset.setValue("Net Balance", netBalance);

    // Create the pie chart
    JFreeChart chart = ChartFactory.createPieChart("Statistical Data", pieDataset);
    PiePlot plot = (PiePlot) chart.getPlot();

    // Display the chart in a ChartFrame
    ChartFrame frame = new ChartFrame("Statistical Data", chart);
    frame.setVisible(true);
    frame.setSize(516, 306);

    } else {
    if (table2.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, "Table is empty.");
    } else {
        JOptionPane.showMessageDialog(this, "Please select a single row for update.");
    }
    }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_eraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eraseActionPerformed
    // Get the model for table2
    DefaultTableModel tblModel = (DefaultTableModel) table2.getModel();

    // Check if a row is selected in table2
    int selectedRow = table2.getSelectedRow();

    if (selectedRow != -1) {
    try {
        // Identify the row to be deleted
        String dataToDelete = (String) tblModel.getValueAt(selectedRow, 0);  // Assume first column contains the unique identifier
        tblModel.removeRow(selectedRow);

        // Read the file and rewrite it without the deleted data
        File inputFile = new File("btn_add.txt");
        BufferedReader reader = new BufferedReader(new FileReader(inputFile));
        StringBuilder updatedContent = new StringBuilder();

        String currentLine;
        while ((currentLine = reader.readLine()) != null) {
            if (!currentLine.startsWith(dataToDelete + ",")) {
                updatedContent.append(currentLine).append(System.lineSeparator());
            }
        }

        reader.close();

        // Write the updated content back to the same file
        FileWriter writer = new FileWriter(inputFile);
        writer.write(updatedContent.toString());
        writer.close();

        JOptionPane.showMessageDialog(this, "Row deleted from Table and file successfully.");
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    } else {
    // Handle cases where no rows are selected
    if (table2.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, "Table is empty.");
    } else {
        JOptionPane.showMessageDialog(this, "Please select a row from Table for deletion.");
    }
    }
    }//GEN-LAST:event_btn_eraseActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
       // Check if any field is empty
    String name = txt_name.getText().trim();
    String incomeText = txt_income.getText().trim();
    String expensesText = txt_expenses.getText().trim();

    if (name.isEmpty() || incomeText.isEmpty() || expensesText.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Oops! You missed something! Fill out all fields to keep the rizz!");
    } else {
    try {
        // Parse the input values
        int income = Integer.parseInt(incomeText);
        int expenses = Integer.parseInt(expensesText);
        
        // Display the values in lbl_income and lbl_expenses
        lbl_income.setText("RM" + " " + income);
        lbl_expenses.setText("RM" + " " + expenses);

        // Calculate net balance
        int netBalance = income - expenses;

        // Create a pie chart dataset
        lbl_netbalance.setText("RM" + " " + netBalance);
        DefaultPieDataset pieDataset = new DefaultPieDataset();
        pieDataset.setValue("Income", income);
        pieDataset.setValue("Expenses", expenses);
        pieDataset.setValue("Net Balance", netBalance);

        // Create the pie chart
        JFreeChart chart = ChartFactory.createPieChart("Statistical Data", pieDataset);
        PiePlot plot = (PiePlot) chart.getPlot();

        // Display the chart in a ChartFrame
        ChartFrame frame = new ChartFrame("Statistical Data", chart);
        frame.setVisible(true);
        frame.setSize(516, 306);

        // Prepare the result string (no labels)
        String result = name + "," + income + "," + expenses + "," + netBalance;

        // Write the data to the file
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("btn_add.txt", true))) {
            writer.write(result);
            writer.newLine();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error saving to file: " + ex.getMessage());
        }

        // Insert the data at the top of the JTable (table2)
        DefaultTableModel model = (DefaultTableModel) table2.getModel();
        model.insertRow(0, new Object[]{name, + income, + expenses, + netBalance});

        // Success message
        JOptionPane.showMessageDialog(null, "Naise! Your record’s locked in, and you've scored some aura points!");

        // Clear the text fields after adding the data
        txt_name.setText("");
        txt_income.setText("");
        txt_expenses.setText("");

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(null, "Please enter valid numbers for income and expenses.");
    }
    }
    }//GEN-LAST:event_btn_submitActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        txt_income.setText(null);
        txt_expenses.setText(null);
        txt_name.setText(null);
        lbl_income.setText(null);
        lbl_expenses.setText(null);
        lbl_netbalance.setText(null);
    }//GEN-LAST:event_btn_clearActionPerformed

    private void table2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table2MouseClicked
        // TODO add your handling code here:
        // Get the selected row index
        int selectedRow = table2.getSelectedRow();

        // Ensure the selected row index is valid
        if (selectedRow != -1) {
            // Retrieve data from the selected row
            String name = table2.getValueAt(selectedRow, 0).toString(); // Assuming name is in column 0
            String income = table2.getValueAt(selectedRow, 1).toString(); // Assuming income is in column 1
            String expenses = table2.getValueAt(selectedRow, 2).toString(); // Assuming expenses is in column 2

            // Set the retrieved values into the text fields
            txt_name.setText(name);
            txt_income.setText(income);
            txt_expenses.setText(expenses);
        }
    }//GEN-LAST:event_table2MouseClicked

    private void btn_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enterActionPerformed
       try {
    // Parse the input values
    double currentSavings = Double.parseDouble(txt_saving.getText());
    double monthlyContribution = Double.parseDouble(txt_monthly.getText());
    double targetAmount = Double.parseDouble(txt_amount.getText());
    String item = txt_item.getText();  // Get the item name from the txt_item field

    // Calculate the number of months required
    if (monthlyContribution > 0) {
        double monthsRequired = (targetAmount - currentSavings) / monthlyContribution;
        String result;

        if (monthsRequired <= 0) {
            result = "You already have enough savings for " + item + "!";
        } else {
            // Display months and years if applicable
            result = "You will be able to buy your " + item + " in " + Math.ceil(monthsRequired) + " month(s)";
            
            // If more than 12 months, also display in years
            if (monthsRequired > 12) {
                double yearsRequired = monthsRequired / 12;
                result += " (" + Math.ceil(yearsRequired) + " year(s))";
            }
        }

        txt_result.setText(result);

        // Write all inputs and the result to the file
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("btn_add.txt", true))) {
            writer.write("Item: " + item);
            writer.newLine();
            writer.write("Current Savings: RM " + currentSavings);
            writer.newLine();
            writer.write("Monthly Contribution: RM " + monthlyContribution);
            writer.newLine();
            writer.write("Target Amount: RM " + targetAmount);
            writer.newLine();
            writer.write(result);  // Write the calculated result to the file
            writer.newLine();  // Add a new line for separation
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error saving to file: " + ex.getMessage());
        }
    } else {
        txt_result.setText("Monthly contribution must be greater than 0.");
    }
    } catch (NumberFormatException ex) {
    // Handle invalid input
    txt_result.setText("Please enter valid numbers.");
    }
    }//GEN-LAST:event_btn_enterActionPerformed

    private void btn_undoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_undoActionPerformed
        // TODO add your handling code here:
        txt_saving.setText(null);
        txt_monthly.setText(null);
        txt_amount.setText(null);
        txt_item.setText(null);
        txt_result.setText(null);
    }//GEN-LAST:event_btn_undoActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedComponent(jPanel1);
    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_next1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_next1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedComponent(jPanel3);
    }//GEN-LAST:event_btn_next1ActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btn_backActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedComponent(jPanel1);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserdashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserdashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserdashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserdashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserdashboardForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_enter;
    private javax.swing.JButton btn_erase;
    private javax.swing.JButton btn_logout2;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_next1;
    private javax.swing.JButton btn_submit;
    private javax.swing.JButton btn_undo;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_expenses;
    private javax.swing.JLabel lbl_income;
    private javax.swing.JLabel lbl_netbalance;
    private javax.swing.JTable table2;
    private javax.swing.JTextField txt_amount;
    private javax.swing.JTextField txt_expenses;
    private javax.swing.JTextField txt_income;
    private javax.swing.JTextField txt_item;
    private javax.swing.JTextField txt_monthly;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextArea txt_result;
    private javax.swing.JTextField txt_saving;
    // End of variables declaration//GEN-END:variables
}